// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
import { app, BrowserWindow, dialog, ipcMain, Menu, MenuItemConstructorOptions, webFrame } from "electron"
import 'reflect-metadata';
import _, { clone, cloneDeep } from "lodash";
import { fileName, getAssetPath } from "./../src/helpers";
import stripJsonTrailingCommas from 'strip-json-trailing-commas';

let mainWindow: BrowserWindow | null;

declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

import * as fs from 'fs';
import * as path from 'path';
import { SpriteEditor } from "./spriteEditor/spriteEditor";

const isProd = process.env.NODE_ENV === "production";
const basePath = isProd ? process.resourcesPath : app.getAppPath()
let isLevelEditor = process.argv.length >= 2 && process.argv[2] === "levelEditor";
let forceClose = false;

let configPath = "";
let assetPath = "assets";
let spriteFolderName = "sprites";
let spritesheetFolderName = "spritesheets";
let levelFolderName = "maps";
let isMapSpritePath = false;

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
export function createWindow() {
	// Create the browser window.
	mainWindow = new BrowserWindow({
		icon: path.join(basePath, "favicon.png"),
		width: 1280,
		height: 720,
		title: isLevelEditor ? "MMXOD Map Editor" : "MMXOD Sprite Editor",
		backgroundColor: "white",
		webPreferences: {
			nodeIntegration: true,
			contextIsolation: true,
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
			webSecurity: false
		}
	});
	//mainWindow.maximize();
	// and load the index.html of the app.
	mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

	/*if (!isProd) {
		mainWindow.webContents.openDevTools();
	} else {
		//@ts-ignore
		let menu = Menu.buildFromTemplate(template);
		Menu.setApplicationMenu(menu);
	}*/
	Menu.setApplicationMenu(null);

	mainWindow.on("close", function (e) {
		if (forceClose) {
			return;
		}
		mainWindow?.webContents?.send("requestDirtyState");
		e.preventDefault();
	});

	mainWindow.on("closed", () => {
		mainWindow = null;
	});

	// Open the DevTools.
	//mainWindow.webContents.openDevTools();
}

export function saveSpriteHelper(req: any) {
	let name = req.name;
	delete req["name"];
	let jsonStr = JSON.stringify(req);
	let savePath = getSpritePath() + name + ".json";
	// console.log("Saving sprite to " + savePath);
	fs.writeFileSync(savePath, jsonStr);
}

export function mapName(filepath: string) {
	if (!filepath) return filepath;
	let pieces = filepath.split("/");
	if (filepath.endsWith("mirrored.json")) {
		return pieces[pieces.length - 2] + "_mirrored";
	}
	return pieces[pieces.length - 2];
}

export function onConfigModFolderChange(config: any) {
	if (config.isInMapModFolder) {
		levelFolderName = "maps_custom";
	}
	else {
		levelFolderName = "maps";
	}

	if (config.isInSpriteModFolder && !isLevelEditor) {
		spriteFolderName = "sprites_visualmods";
	}
	else {
		spriteFolderName = "sprites";
	}
}

export function getSpritePath() {
	return assetPath + `/${spriteFolderName}/`;
}

export function getSpritesheetPath() {
	return assetPath + `/${spritesheetFolderName}/`;
}

export function walkSync(dir: string, filelist: string[]) {
	let files = fs.readdirSync(dir);
	filelist = filelist || [];
	files.forEach(function (file) {
		if (fs.statSync(dir + file).isDirectory()) {
			filelist = walkSync(dir + file + '/', filelist);
		}
		else {
			filelist.push(dir + file);
		}
	});
	return filelist;
};

export function getSpriteHelper(dirname: string, filename: string) {
	if (!filename.endsWith(".json")) return undefined;
	let content = fs.readFileSync(dirname + filename, "utf-8");
	let sprite = jsonParseHelper(content);
	sprite.name = filename.split(".")[0];
	sprite.spritesheetPath = fileName(sprite.spritesheetPath);
	if (dirname.includes("/maps_custom/")) {
		let customMapName = dirname.split("/maps_custom/")[1].split("/")[0];
		sprite.customMapName = customMapName;
	}
	return sprite;
}

export function getSpritesHelper(dirname: string) {
	let sprites: any[] = [];
	let fileNames = fs.readdirSync(dirname);
	for (let filename of fileNames) {
		let sprite = getSpriteHelper(dirname, filename);
		if (sprite) {
			sprites.push(sprite);
		}
	}
	return sprites;
}

export function getSpritesheetsHelper(dirname: string) {
	let paths: string[] = [];
	let fileNames = fs.readdirSync(dirname);
	for (let filename of fileNames) {
		if (filename.toLowerCase().endsWith(".png")) {
			paths.push(dirname + filename);
		}
	}
	return paths;
}

export function jsonParseHelper(jsonStr: string) {
	jsonStr = stripJsonTrailingCommas(jsonStr);
	const data = JSON.parse(jsonStr);
	return data;
}

export let api = {
	sendHasDirty: (isDirty: boolean) => {
		if (!mainWindow) return;
		if (isDirty) {
			let choice = dialog.showMessageBoxSync(mainWindow, {
				type: 'question',
				buttons: ['Yes', 'No'],
				title: 'Confirm Quit',
				message: 'You have unsaved changes. Are you sure you want to quit?\nAny unsaved changes will be lost.'
			});
			if (choice === 0) {
				forceClose = true;
				mainWindow.close();
			}
		} else {
			forceClose = true;
			mainWindow.close();
		}
	},

	showDialog: (title: string, message: string, buttons: string[], isError: boolean, isCrash: boolean) => {
		if (!mainWindow) return;
		let selectedButtonIndex = dialog.showMessageBoxSync(mainWindow, {
			buttons: buttons,
			message: message,
			title: title,
		});
		return selectedButtonIndex;
	},

	getEditorType: () => {
		let type = 0;
		if (isLevelEditor) {
			type = 1;
		}
		return type;
	},

	getCustomMapContext: () => {
		if (isMapSpritePath) {
			return mapName(spriteFolderName);
		}
		return "";
	},

	getConfig: () => {
		if (!mainWindow) return;
		configPath = "config.json";
		let documentsPath = app.getPath("documents").replace(/\\/g, "/");
		let documentsConfigPath = documentsPath + "/MMXOD Editor";
		if (fs.existsSync(documentsConfigPath)) {
			configPath = documentsConfigPath + "/" + configPath;
		}

		let config: any = {
			assetPath: "",
			allowUnsupportedActions: isProd === false,
			lastSpriteFilterMode: "contains",
			isInMapModFolder: true,
			isInSpriteModFolder: true,
		};

		if (!fs.existsSync(configPath)) {
			fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
		}
		else {
			config = jsonParseHelper(fs.readFileSync(configPath, "utf-8"));
		}

		if (!isMapSpritePath) {
			onConfigModFolderChange(config);
		}

		if (config.assetPath) {
			assetPath = config.assetPath;
		}
		else {
			dialog.showMessageBoxSync(mainWindow, {
				message: "You will be prompted to select an assets folder that contains the sprite and map folders.",
				title: "First time setup required",
			});
			var paths = dialog.showOpenDialogSync({
				title: "Please select an assets folder.",
				properties: ['openDirectory'],
			});
			if (paths && paths[0]) {
				assetPath = paths[0].replace(/\\/g, "/");
			} else {
				assetPath = "";
			}

			if (!assetPath) {
				throw "Asset path not selected. Cannot proceed.";
			}

			config.assetPath = assetPath;
			fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
		}

		config.isProd = isProd;
		config.version = app.getVersion();
		return config;
	},

	saveConfig: (config: any) => {
		fs.writeFileSync(configPath, config);
	},

	saveConfigAndReload: (message: any) => {
		if (!mainWindow) return;
		let selectedButtonIndex = 0;
		if (message.isDirty) {
			selectedButtonIndex = dialog.showMessageBoxSync(mainWindow, {
				buttons: ["OK", "Cancel"],
				message: "You will lose any unsaved changes.",
				title: "Are you sure?",
			});
		}

		if (selectedButtonIndex === 0) {
			fs.writeFileSync(configPath, message.config);
			onConfigModFolderChange(message.config);
			mainWindow.reload();
		}
	},

	zoom: (zoom: number) => {
		webFrame.setZoomFactor(zoom);
	},

	reload: (message: any) => {
		if (!mainWindow) return;
		let selectedButtonIndex = 0;
		if (message.isDirty) {
			selectedButtonIndex = dialog.showMessageBoxSync(mainWindow, {
				buttons: ["OK", "Cancel"],
				message: "You will lose any unsaved changes.",
				title: "Are you sure?",
			});
		}
		if (selectedButtonIndex === 0) {
			if (isMapSpritePath) {
				isMapSpritePath = false;
				isLevelEditor = true;
			}
			mainWindow.reload();
		}
	},

	getIsMapSpriteEditor: () => {
		return isMapSpritePath;
	},

	setupMapSpriteEditor: (message: any) => {
		if (!mainWindow) return;
		let selectedButtonIndex = 0;
		if (message.isDirty) {
			selectedButtonIndex = dialog.showMessageBoxSync(mainWindow, {
				buttons: ["OK", "Cancel"],
				message: "You will lose any unsaved changes.",
				title: "Are you sure?",
			});
		}
		let mapFolderPath = path.dirname(message.path) + "/sprites";
		let spritesheetPath: string = assetPath + "/" + mapFolderPath + "/spritesheet.png";
		if (!fs.existsSync(spritesheetPath)) {
			throw `Sprites folder "${spritesheetPath}" does not exist with a spritesheet.png file.`;
		}
		if (selectedButtonIndex === 0) {
			isLevelEditor = false;
			isMapSpritePath = true;
			spriteFolderName = mapFolderPath;
			spritesheetFolderName = mapFolderPath;
			mainWindow.reload();
		}
	},

	setupMapEditorFromSpr: (message: any) => {
		if (!mainWindow) return;
		let selectedButtonIndex = 0;
		if (message.isDirty) {
			selectedButtonIndex = dialog.showMessageBoxSync(mainWindow, {
				buttons: ["OK", "Cancel"],
				message: "You will lose any unsaved changes.",
				title: "Are you sure?",
			});
		}
		if (selectedButtonIndex === 0) {
			isLevelEditor = true;
			isMapSpritePath = false;
			spriteFolderName = "sprites";
			spritesheetFolderName = "spritesheets";
			mainWindow.reload();
		}
	},

	getSprites: () => {
		let sprites = []; 
		// If not in the custom map load base sprites.
		if (!isLevelEditor || levelFolderName !== "maps_custom") {
			sprites = getSpritesHelper(getSpritePath());
		}
		// Get map-specific sprites.
		if (isLevelEditor) {
			let dirname = assetPath + `/${levelFolderName}/`;
			let filePaths: string[] = walkSync(dirname, []);
			for (let filepath of filePaths) {
				if (!filepath.includes("/sprites/")) continue;
				if (!filepath.endsWith(".json")) continue;
				let mapSprite = getSpriteHelper(path.dirname(filepath) + "/", path.basename(filepath));
				if (mapSprite) {
					let pieces = filepath.split('/');
					let mapName = pieces[pieces.length - 3]
					mapSprite.name = mapName + ":" + mapSprite.name;
					sprites.push(mapSprite);
				}
			}
		}

		return sprites;
	},

	getSpritesheets: () => {
		// Load default sprites only for built-in maps or the sprite editor.
		let spritesheets = [];
		if (!isLevelEditor || levelFolderName !== "maps_custom") {
			spritesheets = getSpritesheetsHelper(getSpritesheetPath());
		}
		// Get custom map spritesheets
		if (isLevelEditor) {
			// Search sub-sprites.
			let dirname = assetPath + `/${levelFolderName}/`;
			let filePaths: string[] = walkSync(dirname, []);
			for (let filepath of filePaths) {
				if (!filepath.includes("/sprites/")) continue;
				if (filepath.toLowerCase().endsWith(".png")) {
					spritesheets.push(filepath);
				}
			}
		}

		return spritesheets;
	},

	saveSprite: (message: any) => {
		saveSpriteHelper(message);
	},

	saveSprites: (message: any) => {
		for (var sprite of message) {
			saveSpriteHelper(sprite);
		}
	},

	getLevels: () => {
		let dirname = assetPath + `/${levelFolderName}/`;
		let levels: any[] = [];
		let filePaths: string[] = walkSync(dirname, []);

		for (let filepath of filePaths) {
			if (!filepath.endsWith(".json")) continue;
			if (filepath.includes("/sprites/")) continue;
			let content = fs.readFileSync(filepath, 'utf-8');
			let level = jsonParseHelper(content);
			level.name = mapName(filepath);
			level.path = getAssetPath(filepath);
			levels.push(level);
		}
		return levels;
	},

	getBackgrounds: () => {
		var paths: string[] = [];
		let filePaths = walkSync(assetPath + `/${levelFolderName}/`, []);
		for (let filepath of filePaths) {
			if (!filepath.endsWith(".png")) continue;
			if (filepath.includes("thumbnails")) continue;
			paths.push(filepath);
		}
		filePaths = walkSync(assetPath + "/maps_shared/", []);
		for (let filename of filePaths) {
			if (!filename.endsWith(".png")) continue;
			if (filename.includes("thumbnails")) continue;
			paths.push(filename);
		}
		return paths;
	},

	saveLevel: (message: Record<string, any>) => {
		let jsonStr = JSON.stringify(message, null, 2);
		let finalPath = assetPath + "/" + message.path;
		fs.writeFileSync(finalPath, jsonStr);
	},

	saveMirroredLevel: (message: Record<string, any>) => {
		let jsonStr = JSON.stringify(message, null, 2);
		let finalPath = assetPath + "/" + message.path;
		fs.writeFileSync(finalPath, jsonStr);
		return message;
	},

	addLevel: (message: Record<string, any>) => {
		let folderPath = assetPath + `/${levelFolderName}/` + message.name;
		if (!fs.existsSync(folderPath)) {
			fs.mkdirSync(folderPath);
		}
		let finalPath = folderPath + "/map.json";
		message.path = `${levelFolderName}/${message.name}/map.json`;
		let jsonStr = JSON.stringify(message, null, 2);
		fs.writeFileSync(finalPath, jsonStr);
		return message;
	},

	loadExtrenalFile: (filePath: string) => {
		let file = fs.readFileSync(filePath, "utf8");
		return file;
	},

	readDirExt: (folderPath: string) => {
		let file = fs.readdirSync(folderPath);
		return file;
	},

	mountSpriteMenu(flags: boolean[]) {
		let template: MenuItemConstructorOptions[] = [{
			label: "&File",
			submenu: [{
				label: "Open", accelerator: "Ctrl+Alt+O", registerAccelerator: true,
				click: () => {
					if (openNewFolder()) { mainWindow?.webContents?.send("reloadBT") }
				}
			}, {
				label: "Reload", click: () => { mainWindow?.webContents?.send("reloadBT") },
				accelerator: "Ctrl+F5", registerAccelerator: true
			}, {
				label: "Save all", click: () => { mainWindow?.webContents?.send("saveAllBT") },
				accelerator: "Ctrl+Alt+S", registerAccelerator: false,
				enabled: flags[2]
			}]
		}, {
			label: "&Edit",
			submenu: [
				{
					label: "Undo", click: () => { mainWindow.webContents?.send("undoBT") },
					accelerator: "Ctrl+Z", registerAccelerator: false
				}, {
					label: "Redo", click: () => { mainWindow.webContents?.send("redoBT") },
					accelerator: "Ctrl+Y", registerAccelerator: false
				}, {
					label: "Ghost mode", click: () => { mainWindow.webContents?.send("ghostModeBT") },
					accelerator: "G", registerAccelerator: false
				}, {
					label: "Remove ghost", click: () => { mainWindow.webContents?.send("removeGhostBT") },
					accelerator: "Escape", registerAccelerator: false
				}
			]
		}, {
			label: "&Help",
			submenu: [
				{
					label: "Hotkeys", click: () => { mainWindow.webContents?.send("helpBT") },
					accelerator: "F1", registerAccelerator: false
				}, {
					role: "toggleDevTools", accelerator: "F12"
				}, {
					label: "Asset Path: " + assetPath, enabled: false
				}, {
					label: "Version " + app.getVersion(), enabled: false
				}
			]
		}];
		if (!flags[1]) {
			template[template.length] = {
				label: flags[0] ? "☑️ Visualmods" : "❎ Visualmods", id: "vmod",
				accelerator: "Ctrl+F1", registerAccelerator: false,
				click: () => {
					mainWindow?.webContents?.send("visualModBT");
				}
			};
		} else {
			template[template.length] = {
				label: "Map mode", id: "vmap",
				accelerator: "Ctrl+F1", registerAccelerator: false,
				click: () => {
					mainWindow?.webContents?.send("spriteToMapBT");
				}
			};
		}
		let menu = Menu.buildFromTemplate(template);
		mainWindow.setMenu(menu);
	},

	mountMapMenu(flags: boolean[]) {
		let template: MenuItemConstructorOptions[] = [{
			label: "&File",
			submenu: [{
				label: "Open", accelerator: "Ctrl+Alt+O", registerAccelerator: true,
				click: () => {
					if (openNewFolder()) { mainWindow?.webContents?.send("reloadBT") }
				}
			}, {
				label: "Reload", click: () => { mainWindow?.webContents?.send("reloadBT") },
				accelerator: "Ctrl+F5", registerAccelerator: true
			}]
		}, {
			label: "&Edit",
			submenu: [
				{
					label: "Undo", click: () => { mainWindow.webContents?.send("undoBT") },
					accelerator: "Ctrl+Z", registerAccelerator: false
				}, {
					label: "Redo", click: () => { mainWindow.webContents?.send("redoBT") },
					accelerator: "Ctrl+Y", registerAccelerator: false
				}, {
					label: "Snap shape", click: () => { mainWindow.webContents?.send("copyShapeBT") },
					accelerator: "E", registerAccelerator: false
				}, {
					label: "Show bounds", click: () => { mainWindow.webContents?.send("showBoundsBT") },
					accelerator: "B", registerAccelerator: false
				}/*, {
					label: "Movel All", 
					click: () => { mainWindow.webContents?.send("moveAllBT") },
					accelerator: "Ctrl+M", registerAccelerator: false
				},*/
			]
		}, {
			label: "&Help",
			submenu: [
				{
					label: "Hotkeys", click: () => { mainWindow.webContents?.send("helpBT") },
					accelerator: "F1", registerAccelerator: false
				}, {
					role: "toggleDevTools", accelerator: "F12"
				}, {
					label: "Asset Path: " + assetPath, enabled: false
				}, {
					label: "Version " + app.getVersion(), enabled: false
				}
			]
		}];
		template[template.length] = {
			label: flags[0] ? "☑️ Custom  maps" : "❎ Custom  maps", id: "vmod",
			accelerator: "Ctrl+F1", registerAccelerator: false,
			click: () => {
				mainWindow?.webContents?.send("customMapsBT");
			}
		};
		template[template.length] = {
			label: "Edit map sprites", id: "vspr",
			accelerator: "Ctrl+F2", registerAccelerator: false,
			click: () => {
				mainWindow?.webContents?.send("editSpritesBT");
			}
		};
		let menu = Menu.buildFromTemplate(template);
		mainWindow.setMenu(menu);
	}
}

export function openNewFolder() : boolean {
	var config = api.getConfig();
	var paths = dialog.showOpenDialogSync({
		title: "Please select an assets folder.",
		properties: ['openDirectory'],
	});
	if (paths && paths[0]) {
		assetPath = paths[0].replace(/\\/g, "/");
	} else {
		assetPath = "";
	}

	if (!assetPath) {
		return false;
	}

	config.assetPath = assetPath;
	fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
	return true;
}

async function registerListeners() {
	for (let key of Object.keys(api)) {
		let func = api[key] as Function;
		ipcMain.on(key, (_, ...args: any[]) => {
			try {
				let result = func(...args);
				mainWindow?.webContents?.send(key, result);
			}
			catch (error) {
				mainWindow?.webContents?.send(key + "Error", error);
			}
		});
	}
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)
	.whenReady()
	.then(registerListeners)
	.catch(e => console.error(e));

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
})

// On OS X it's common to re-create a window in the app when the
// dock icon is clicked and there are no other windows open.
app.on('activate', () => {
	if (BrowserWindow.getAllWindows().length === 0) {
		createWindow();
	}
})

export function updateSpriteMenuAlt(menu: Menu, flags: boolean[]): Menu {
	let vmod = menu.getMenuItemById("vmod");
	if (flags[0]) {
		vmod.label = "☑️ Visualmods";
	} else {
		vmod.label = "❎ Visualmods";
	}
	return menu;
}